% Script generated by Brainstorm (28-Oct-2022)


for i = 0:99 
    files= dir(['/Users/admin/Downloads/SimulatedData/frequency_new_new_new/0.5_250_PSD_mat/', num2str(i) '/*.mat']);

    for n = 1:500
        
        sFiles= [files(n).folder, '/', files(n).name];
                 % open every simulated file
        example=load(sFiles);
        % Save the fields of structure 'example' as *individual variables* in a file
        % called data_block001_copy.mat (basically replace the original file with the new format given by the variable 'example')
        
        save('/Users/admin/Documents/brainstorm_db/TutorialIntroduction/data/Subject01/@rawS01_AEF_20131218_01_600Hz_resample/timefreq_psd_221111_1501.mat','-struct', 'example') % save filename & variable

        % Input files
        sFiles = {... 
            'Subject01/@rawS01_AEF_20131218_01_600Hz_resample/timefreq_psd_221111_1501.mat'};


% Process: specparam: Fitting oscillations and 1/f
output = bst_process('CallProcess', 'process_fooof', sFiles, [], ...
    'implementation', 'matlab', ...  % Matlab
    'freqrange',      [1, 40], ...
    'powerline',      '60', ...  % 60 Hz
    'peaktype',       'gaussian', ...  % Gaussian
    'peakwidth',      [0.5, 12], ...
    'maxpeaks',       3, ...
    'minpeakheight',  3, ...
    'proxthresh',     2, ...
    'apermode',       'fixed', ...  % Fixed
    'guessweight',    'none', ...  % None
    'sorttype',       'param', ...  % Peak parameters
    'sortparam',      'frequency', ...  % Frequency
    'sortbands',      {'delta', '2, 4'; 'theta', '5, 7'; 'alpha', '8, 12'; 'beta', '15, 29'; 'gamma1', '30, 59'; 'gamma2', '60, 90'});


        filename='/Users/admin/Documents/brainstorm_db/TutorialIntroduction/data/Subject01/@rawS01_AEF_20131218_01_600Hz_resample/timefreq_psd_221111_1501_specparam.mat';
  
        copyfile(filename, ['/Users/admin/Downloads/SimulatedData/frequency_new_new_new/0.5_250_PSD_mat/', num2str(i) '/timefreq_fooof_221110_', num2str(n), '.mat'])
        delete(filename)
        
        db_reload_database()
     

    end

    
end

